import { db, auth } from './firebase-config.js';
import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js';
import { doc, setDoc, collection, getDocs, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js';
let CODES=[], RESULTS=[];
onAuthStateChanged(auth,u=>{loginCard.classList.toggle('hide',!!u);panel.classList.toggle('hide',!u)});
window.adminLogin=()=>signInWithEmailAndPassword(auth,email.value.trim(),pass.value).catch(e=>alert('Login failed: '+e.message));
window.logout=()=>signOut(auth);
function opt(line){for(let p of [/^([A-Da-d])[\.)]\s*(.*)$/,/^([A-Da-d])\s*[:\-]\s*(.*)$/,/^(ఎ|బి|సి|డి|అ|ఆ|ఇ|ఈ)[\.)]\s*(.*)$/,/^(ఎ|బి|సి|డి|అ|ఆ|ఇ|ఈ)\s*[:\-]\s*(.*)$/]){let m=line.match(p);if(m){let x=m[1],i=/[A-Da-d]/.test(x)?'ABCD'.indexOf(x.toUpperCase()):{'ఎ':0,'అ':0,'బి':1,'ఆ':1,'సి':2,'ఇ':2,'డి':3,'ఈ':3}[x];return{i,t:m[2]}}}return null}
function isQ(l){return /^(\d+[\.)]|Q\d+[\.)]|ప్రశ్న\s*\d+)/i.test(l)}
function cleanQ(l){return l.replace(/^Q\d+[\.)]\s*/i,'').replace(/^ప్రశ్న\s*\d+[\.)]?\s*/,'').replace(/^\d+[\.)]\s*/,'').trim()}
function parseBits(raw){let lines=raw.replace(/\u200b/g,'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),qs=[],subject='General',cur=null;function flush(){if(cur&&cur.o.length===4){if(cur.a==null)cur.a=0;cur.q=cur.q.trim();qs.push(cur)}cur=null}for(let line of lines){if(line.startsWith('*')&&line.endsWith('*')){subject=line.replace(/\*/g,'').trim()||subject;continue}if(line==='ఆప్షన్లు:'||line==='UTF DSC EXAM')continue;let an=line.match(/^(సమాధానం|Answer|Ans)[:：]?\s*([A-Da-d])/i);if(an&&cur){cur.a='ABCD'.indexOf(an[2].toUpperCase());continue}let o=opt(line);if(o&&cur){let t=o.t.trim();if(/[●⚫•*]/.test(t))cur.a=o.i;t=t.replace(/[●⚫•*]/g,'').trim();cur.o.push(t);continue}if(isQ(line)){if(cur&&cur.o.length===4)flush();cur={subject,q:cleanQ(line),o:[],a:null};continue}if(cur)cur.q+='\n'+line}flush();return qs}
function gen(n,prefix){let out=[],set=new Set();for(let i=0;i<n;i++){let c;do{c=(prefix||'DSC').toUpperCase()+Math.floor(100000+Math.random()*900000)}while(set.has(c));set.add(c);out.push(c)}return out}
window.uploadExam=async()=>{let id=examId.value.trim().toUpperCase();let qs=parseBits(bits.value);if(!id)return alert('Exam ID enter చేయండి');if(!qs.length)return alert('Questions detect కాలేదు. కనీసం 1 question + 4 options ఉండాలి.');await setDoc(doc(db,'exams',id),{title:title.value.trim()||id,start:start.value,end:end.value,sec:+sec.value||45,marks:+marks.value||1,neg:+neg.value||0,showResult:showResult.value==='yes',shuffleQ:true,shuffleO:true,questions:qs,createdAt:serverTimestamp(),createdBy:auth.currentUser.email,version:'C'},{merge:false});CODES=gen(+count.value||100,prefix.value.trim()||'DSC');for(const c of CODES){await setDoc(doc(db,'exams',id,'codes',c),{code:c,examId:id,used:false,active:true,createdAt:serverTimestamp(),createdBy:auth.currentUser.email,studentName:'',phone:''},{merge:false})}codesBox.textContent=CODES.join('\n');leadExamId.value=id;status.innerHTML='<span class="ok">'+qs.length+' questions uploaded. '+CODES.length+' codes saved in Firestore.</span>'};
window.copyCodes=()=>{navigator.clipboard.writeText(CODES.join('\n'));alert('Codes copied')};
window.downloadCodes=()=>download('S.No,Exam ID,Code\n'+CODES.map((c,i)=>`${i+1},${examId.value.trim().toUpperCase()},${c}`).join('\n'),'codes.csv');
window.loadSample=()=>bits.value='*Sample*\n1. భారత రాజధాని ఏది?\nA) ముంబై\nB) ఢిల్లీ ●\nC) చెన్నై\nD) హైదరాబాద్\n\n2. 2 + 2 ఎంత?\nA) 3\nB) 4 ●\nC) 5\nD) 6';
window.loadResults=async()=>{let id=leadExamId.value.trim().toUpperCase();let snap=await getDocs(collection(db,'exams',id,'attempts'));RESULTS=[];snap.forEach(d=>RESULTS.push(d.data()));RESULTS.sort((a,b)=>b.score-a.score||((a.submittedAt?.seconds||0)-(b.submittedAt?.seconds||0)));let h='<table><tr><th>Rank</th><th>Name</th><th>Phone</th><th>Code</th><th>Score</th><th>Total</th><th>%</th><th>Warnings</th></tr>';RESULTS.forEach((r,i)=>h+=`<tr class="${i===0?'top1':''}"><td>${i+1}</td><td>${r.name||''}</td><td>${r.phone||''}</td><td>${r.code||''}</td><td>${r.score}</td><td>${r.total}</td><td>${r.pct}</td><td>${r.warnings||0}</td></tr>`);leader.innerHTML=h+'</table>';renderTop10()};
function renderTop10(){let t='🏆 DSC TEST TOP 10\n\n';RESULTS.slice(0,10).forEach((r,i)=>t+=`${i+1}. ${r.name||'Student'} - ${r.score}/${r.total} (${r.pct})\n`);top10.textContent=t}
window.copyTop10=()=>navigator.clipboard.writeText(top10.textContent);
window.downloadResults=()=>download('Rank,Name,Phone,Code,Score,Total,Percentage,Correct,Wrong,Attempted,Warnings\n'+RESULTS.map((r,i)=>`${i+1},"${r.name||''}","${r.phone||''}",${r.code||''},${r.score},${r.total},${r.pct},${r.correct},${r.wrong},${r.attempted},${r.warnings||0}`).join('\n'),'results.csv');
function download(text,name){let b=new Blob([text],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click()}

