import { db, auth } from './firebase-config.js';
import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js';
import { doc, setDoc, collection, getDocs, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js';
let CODES=[],RESULTS=[]; const $=id=>document.getElementById(id);
onAuthStateChanged(auth,u=>{$('loginCard').classList.toggle('hide',!!u);$('panel').classList.toggle('hide',!u)});
window.adminLogin=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('pass').value)}catch(e){alert('Login failed: '+e.message)}};
window.logout=()=>signOut(auth);
function gen(n,prefix){let out=[],set=new Set(),p=(prefix||'DSC').trim().toUpperCase();while(out.length<n){let c=p+Math.floor(100000+Math.random()*900000);if(!set.has(c)){set.add(c);out.push(c)}}return out}
function opt(line){for(const p of [/^([A-Da-d])[\.)]\s*(.*)$/,/^([A-Da-d])\s*[:\-]\s*(.*)$/,/^(ఎ|బి|సి|డి|అ|ఆ|ఇ|ఈ)[\.)]\s*(.*)$/,/^(ఎ|బి|సి|డి|అ|ఆ|ఇ|ఈ)\s*[:\-]\s*(.*)$/]){let m=line.match(p);if(m){let k=m[1],i=/[A-Da-d]/.test(k)?'ABCD'.indexOf(k.toUpperCase()):{'ఎ':0,'అ':0,'బి':1,'ఆ':1,'సి':2,'ఇ':2,'డి':3,'ఈ':3}[k];return{index:i,text:m[2].trim()}}}return null}
function isQ(l){return /^(\d+[\.)]|Q\d+[\.)]|ప్రశ్న\s*\d+)/i.test(l)}
function cleanQ(l){return l.replace(/^Q\d+[\.)]\s*/i,'').replace(/^ప్రశ్న\s*\d+[\.)]?\s*/i,'').replace(/^\d+[\.)]\s*/,'').trim()}
function parseBits(raw){let lines=raw.replace(/\u200b/g,'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),qs=[],subject='DSC',cur=null;function flush(){if(cur&&cur.o.length===4){if(cur.a==null)cur.a=0;cur.q=cur.q.trim();qs.push(cur)}cur=null}for(const line of lines){if(line.startsWith('*')&&line.endsWith('*')){subject=line.replace(/\*/g,'').trim()||'DSC';continue}if(line==='ఆప్షన్లు:'||line==='UTF DSC EXAM')continue;let an=line.match(/^(సమాధానం|Answer|Ans)[:：]?\s*([A-Da-d])/i);if(an&&cur){cur.a='ABCD'.indexOf(an[2].toUpperCase());continue}let o=opt(line);if(o&&cur){let t=o.text;if(/[●⚫•*]/.test(t))cur.a=o.index;t=t.replace(/[●⚫•*]/g,'').trim();cur.o.push(t);continue}if(isQ(line)){if(cur&&cur.o.length===4)flush();cur={subject,q:cleanQ(line),o:[],a:null};continue}if(cur)cur.q+='\n'+line}flush();return qs}
function medal(rank){return rank===1?'🥇':rank===2?'🥈':rank===3?'🥉':rank}
function formatTime(sec){sec=Number(sec||0);return Math.floor(sec/60)+'m '+(sec%60)+'s'}
function enrichRanks(rows){rows.sort((a,b)=>{if((b.score||0)!==(a.score||0))return(b.score||0)-(a.score||0);if((a.timeTakenSec||999999)!==(b.timeTakenSec||999999))return(a.timeTakenSec||999999)-(b.timeTakenSec||999999);return(a.submittedAt?.seconds||0)-(b.submittedAt?.seconds||0)});let lastScore=null,lastRank=0;rows.forEach((r,i)=>{if(lastScore===null||r.score!==lastScore){lastRank=i+1;lastScore=r.score}r.rank=lastRank;r.medal=medal(lastRank)});return rows}
function renderStats(rows){let total=rows.length,scores=rows.map(r=>Number(r.score||0)),high=total?Math.max(...scores):0,low=total?Math.min(...scores):0,avg=total?(scores.reduce((a,b)=>a+b,0)/total).toFixed(2):0,avgPct=total?(rows.reduce((a,r)=>a+((Number(r.score||0)/Number(r.total||1))*100),0)/total).toFixed(2):0,pass=rows.filter(r=>(Number(r.score||0)/Number(r.total||1))*100>=35).length,fail=total-pass,passPct=total?((pass/total)*100).toFixed(1)+'%':'0%',warn=rows.reduce((a,r)=>a+Number(r.warnings||0),0),avgTime=total?Math.round(rows.reduce((a,r)=>a+Number(r.timeTakenSec||0),0)/total):0;$('statsBox').innerHTML=`<div class="stat"><div class="label">Total Attempts</div><div class="value">${total}</div></div><div class="stat"><div class="label">Highest Score</div><div class="value">${high}</div></div><div class="stat"><div class="label">Lowest Score</div><div class="value">${low}</div></div><div class="stat"><div class="label">Average Score</div><div class="value">${avg}</div></div><div class="stat"><div class="label">Average %</div><div class="value">${avgPct}%</div></div><div class="stat"><div class="label">Pass %</div><div class="value">${passPct}</div></div><div class="stat"><div class="label">Fail Count</div><div class="value">${fail}</div></div><div class="stat"><div class="label">Warnings</div><div class="value">${warn}</div></div><div class="stat"><div class="label">Avg Time</div><div class="value">${formatTime(avgTime)}</div></div>`}
window.uploadExam=async()=>{try{$('status').innerHTML='Uploading...';let id=$('examId').value.trim().toUpperCase();if(!id)return alert('Exam ID enter చేయండి');let questions=parseBits($('bits').value);if(!questions.length){$('status').innerHTML='<span class="bad">Questions detect కాలేదు.</span>';return alert('Questions detect కాలేదు. ప్రతి question కి 4 options ఉండాలి. Correct answer దగ్గర ● పెట్టండి.')}await setDoc(doc(db,'exams',id),{title:$('title').value.trim()||id,start:$('start').value,end:$('end').value,sec:Number($('sec').value)||45,marks:Number($('marks').value)||1,neg:Number($('neg').value)||0,showResult:$('showResult').value==='yes',shuffleQ:true,shuffleO:true,questions,createdAt:serverTimestamp(),createdBy:auth.currentUser?auth.currentUser.email:'admin',version:'D-rank-stats'});CODES=gen(Number($('count').value)||100,$('prefix').value||'DSC');for(const code of CODES){await setDoc(doc(db,'exams',id,'codes',code),{code,examId:id,used:false,active:true,createdAt:serverTimestamp(),createdBy:auth.currentUser?auth.currentUser.email:'admin',studentName:'',phone:''})}$('codesBox').textContent=CODES.join('\n');$('leadExamId').value=id;$('status').innerHTML='<span class="ok">Success: '+questions.length+' questions uploaded. '+CODES.length+' codes generated.</span>';alert('Exam uploaded successfully!')}catch(e){console.error(e);alert('Upload error: '+e.message);$('status').innerHTML='<span class="bad">'+e.message+'</span>'}};
window.copyCodes=async()=>{await navigator.clipboard.writeText(CODES.join('\n'));alert('Codes copied')};
window.downloadCodes=()=>download('S.No,Exam ID,Code\n'+CODES.map((c,i)=>`${i+1},${$('examId').value.trim().toUpperCase()},${c}`).join('\n'),'codes.csv');
window.loadSample=()=>{$('bits').value='1. భారత రాజధాని ఏది?\\nA) ముంబై\\nB) ఢిల్లీ ●\\nC) చెన్నై\\nD) హైదరాబాద్\\n\\n2. 2 + 2 ఎంత?\\nA) 3\\nB) 4 ●\\nC) 5\\nD) 6'};
window.loadResults=async()=>{try{let id=$('leadExamId').value.trim().toUpperCase(),snap=await getDocs(collection(db,'exams',id,'attempts'));RESULTS=[];snap.forEach(d=>RESULTS.push(d.data()));RESULTS=enrichRanks(RESULTS);renderStats(RESULTS);let html='<table><tr><th>Rank</th><th>Name</th><th>Phone</th><th>Code</th><th>Score</th><th>Total</th><th>%</th><th>Time</th><th>Warnings</th><th>Status</th></tr>';RESULTS.forEach(r=>{let pct=(Number(r.score||0)/Number(r.total||1))*100,status=pct>=35?'<span class="pass">PASS</span>':'<span class="fail">FAIL</span>',cls=r.rank===1?'rank1':r.rank===2?'rank2':r.rank===3?'rank3':'';html+=`<tr class="${cls}"><td>${r.medal} ${r.rank}</td><td>${r.name||''}</td><td>${r.phone||''}</td><td>${r.code||''}</td><td>${r.score||0}</td><td>${r.total||0}</td><td>${r.pct||''}</td><td>${formatTime(r.timeTakenSec)}</td><td>${r.warnings||0}</td><td>${status}</td></tr>`});$('leader').innerHTML=html+'</table>';renderTop10()}catch(e){alert('Load results error: '+e.message)}};
function renderTop10(){let t='🏆 KSR DSC TOP 10\\n\\n';RESULTS.slice(0,10).forEach(r=>{t+=`${r.medal} Rank ${r.rank}: ${r.name||'Student'} - ${r.score||0}/${r.total||0} (${r.pct||''})\\n`});$('top10').textContent=t}
window.copyTop10=async()=>{await navigator.clipboard.writeText($('top10').textContent);alert('Top 10 copied')};
window.downloadResults=()=>{let csv='Rank,Name,Phone,Code,Score,Total,Percentage,Correct,Wrong,Attempted,TimeTaken,Warnings,Status\\n'+RESULTS.map(r=>{let pct=(Number(r.score||0)/Number(r.total||1))*100,status=pct>=35?'PASS':'FAIL';return `${r.rank},"${r.name||''}","${r.phone||''}",${r.code||''},${r.score||0},${r.total||0},${r.pct||''},${r.correct||0},${r.wrong||0},${r.attempted||0},${formatTime(r.timeTakenSec)},${r.warnings||0},${status}`}).join('\\n');download(csv,'results_with_rank.csv')};
function download(text,name){let blob=new Blob([text],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click()}
