import { db } from './firebase-config.js';
import { doc, getDoc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js';
let EXAM=null,Q=[],cur=0,ans=[],rev=[],seconds=0,timerInt=null,student='',phone='',code='',eid='',warnings=0,started=false;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function windowCheck(){let now=new Date();if(EXAM.start&&now<new Date(EXAM.start))return 'NOT_STARTED';if(EXAM.end&&now>new Date(EXAM.end))return 'CLOSED';return 'OPEN'}
document.addEventListener('contextmenu',e=>{if(started)e.preventDefault()});document.addEventListener('copy',e=>{if(started)e.preventDefault()});document.addEventListener('visibilitychange',()=>{if(started&&document.hidden){warnings++;warns.innerText=warnings}});
window.studentLogin=async()=>{loginMsg.textContent='';student=stName.value.trim();phone=stPhone.value.trim();eid=stExamId.value.trim().toUpperCase();code=stCode.value.trim().toUpperCase().replace(/\s+/g,'');if(!student||!phone||!eid||!code){alert('Name, Phone, Exam ID, Exam Code అన్ని enter చేయండి');return}try{const ex=await getDoc(doc(db,'exams',eid));if(!ex.exists()){alert('Invalid Exam ID');return}EXAM=ex.data();const cd=await getDoc(doc(db,'exams',eid,'codes',code));if(!cd.exists()){alert('Invalid code. Admin Generated Codes box లో ఉన్న NEW code మాత్రమే వాడండి.');return}const codeData=cd.data();if(codeData.active===false){alert('This code is not active');return}if(codeData.used===true){alert('This code already used');return}const at=await getDoc(doc(db,'exams',eid,'attempts',code));if(at.exists()){alert('Already submitted with this code');return}const w=windowCheck();if(w==='NOT_STARTED'){alert('Exam ఇంకా start కాలేదు');return}if(w==='CLOSED'){alert('Exam closed');return}Q=JSON.parse(JSON.stringify(EXAM.questions||[])).map(q=>({subject:q.subject,q:q.q,o:q.o.map((x,i)=>({text:x,correct:i===q.a}))}));if(!Q.length){alert('Questions not found');return}if(EXAM.shuffleQ)shuffle(Q);if(EXAM.shuffleO)Q.forEach(q=>shuffle(q.o));ans=Array(Q.length).fill(null);rev=Array(Q.length).fill(false);seconds=Q.length*(EXAM.sec||45);mainTitle.innerText=EXAM.title||eid;examTitle.innerText=EXAM.title||eid;login.classList.add('hide');exam.classList.remove('hide');started=true;show();tick();timerInt=setInterval(()=>{seconds--;tick();if(seconds<=0||windowCheck()==='CLOSED')submitExam(true)},1000)}catch(e){alert('Login error: '+e.message)}};
function tick(){let m=Math.floor(seconds/60),s=seconds%60;timer.innerText=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function show(){let q=Q[cur];prog.innerText='Question '+(cur+1)+' of '+Q.length+' | '+(q.subject||'General');let h='<div class="q">'+esc(q.q)+'</div>';q.o.forEach((op,i)=>{h+='<label class="opt"><input type="radio" name="op" '+(ans[cur]===i?'checked':'')+' onchange="sel('+i+')"> '+String.fromCharCode(65+i)+') '+esc(op.text)+'</label>'});qcard.innerHTML=h;pal()}
window.sel=i=>{ans[cur]=i;pal()};window.next=()=>{if(cur<Q.length-1){cur++;show()}};window.prev=()=>{if(cur>0){cur--;show()}};window.mark=()=>{rev[cur]=!rev[cur];pal()};window.go=i=>{cur=i;show()};
function pal(){let h='';for(let i=0;i<Q.length;i++)h+='<div class="num '+(ans[i]!=null?'ans ':'')+(rev[i]?'rev ':'')+(i===cur?'cur':'')+'" onclick="go('+i+')">'+(i+1)+'</div>';palette.innerHTML=h}
window.submitExam=async(auto)=>{if(!auto&&!confirm('Submit చేయాలా?'))return;started=false;if(timerInt)clearInterval(timerInt);let correct=0,wrong=0,attempted=0;Q.forEach((q,i)=>{if(ans[i]!=null){attempted++;if(q.o[ans[i]].correct)correct++;else wrong++}});let score=(correct*(EXAM.marks||1))-(wrong*(EXAM.neg||0));let total=Q.length*(EXAM.marks||1);let pct=Math.round((score/total)*10000)/100+'%';await setDoc(doc(db,'exams',eid,'attempts',code),{name:student,phone,code,examId:eid,score,total,pct,correct,wrong,attempted,warnings,submittedAt:serverTimestamp()});await setDoc(doc(db,'exams',eid,'codes',code),{used:true,studentName:student,phone,usedAt:serverTimestamp()},{merge:true});exam.classList.add('hide');result.classList.remove('hide');result.innerHTML=EXAM.showResult?'<h2>Result Submitted</h2><h3>'+esc(student)+': '+score+'/'+total+'</h3><p>Correct: '+correct+' | Wrong: '+wrong+' | Attempted: '+attempted+'</p>':'<h2>Submitted Successfully</h2><p>Result adminకి save అయింది.</p>'};
